export const SELECTORS = {
  TOGGLE: ".navbar__toggle-icon",
  CONTENT: ".main-content",
  NOTES: ".notes",
  LIST_VIEW: ".navbar__list-icon",
  GRID_VIEW: ".navbar__grid-icon",
  NOTES_CONTAINER: ".notes__container",
  NOTES_PINNED: ".notes__pinned",
  NOTES_UNPINNED: ".notes__others",
  CREATE_NOTE: ".notes__create-note",
  TITLE: ".notes__title",
  TEXT: ".notes__text",
  BTN_GROUP: ".notes__btn-group",
  CANCEL: ".notes__cancel",
  CLOSE_BTN: ".notes__close-btn",
  DIALOG_TITLE: ".notes__dialog-title",
  DIALOG_TEXT: ".notes__dialog-text",
  DIALOG: ".notes__dialog",
  SEARCH: ".navbar__search",
  TRASH_VIEW: ".trash",
  TRASH_NOTES: ".trash__view",
  TRASH_MENU: ".sidebar__trash",
  NOTES_MENU: ".sidebar__notes",
  PINNED_HEADING: ".notes__head-pinned",
  OTHERS_HEADING: ".notes__head-others",
  DIVIDER: ".notes__divider",
};